[WIP] チャット画面作成
Kohei1918/chat-space pull request #3
Opened 2019-02-18 10:19 UTC by Kohei1918

2019-02-18 11:01 UTC, Kohei1918 commented
![screencapture-localhost-3000-chats-2019-02-18-19_51_18](https://user-images.githubusercontent.com/47496204/52946256-f80a4d80-33b6-11e9-8572-317a5cd47c5b.png)
#WHAT
ChatSpaceチャット画面のビューを作成。
#WHY
ChatSpaceの見た目部分を作成する為。

2019-02-18 11:10 UTC, hiroki5123 commented
見本では、
- テキストフィールドに「type a message」のplaceholderが設定されている
- テキストフォームの右側に画像のアイコンがあり、クリックするとfinderが開いて画像を選択することができるようになる
という気がするので、修正をお願い致します。

2019-02-18 11:11 UTC, ghost requested changes

2019-02-18 11:11 UTC, hiroki5123 commented on app/views/messages/index.html.haml
> +
空行がちょっと多いです。。

2019-02-18 11:11 UTC, hiroki5123 commented on config/routes.rb
> +  get "chats" => "messages#index"
resourcesかrootで指定してください。

2019-02-19 05:45 UTC, Kohei1918 commented on app/views/messages/index.html.haml
> +
空白減らしました。

2019-02-19 05:45 UTC, Kohei1918 commented on config/routes.rb
> +  get "chats" => "messages#index"
rootで指定しました。

2019-02-19 05:48 UTC, Kohei1918 commented
[screencapture-localhost-3000-chats-2019-02-18-21_35_10.pdf](https://github.com/Kohei1918/chat-space/files/2878479/screencapture-localhost-3000-chats-2019-02-18-21_35_10.pdf)

レビューありがとうございます。
* テキストフィールドに「type a message」のplaceholderを追記しました。
* テキストフォームの右側に画像のアイコンを追加しました。
上記2箇所を修正致しました。

2019-02-19 05:57 UTC, hzak2xx approved these changes
LGTM

2019-02-19 06:02 UTC, merged